networks:
  wp-back:
    external: true

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    networks:
      - wp-back
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - .docker/caddy/Caddyfile:/etc/caddy/Caddyfile

      # project files
      - htmldata:/srv/htmldata

  redis:
    image: redis:7-alpine
    networks:
      - wp-back
    restart: always

  wp-fpm:
    image: wordpress:6-fpm-alpine
    restart: always
    networks:
      - wp-back
    depends_on:
      - caddy
      - db
    volumes:
      - htmldata:/var/www/html
      - wp-theme:/var/www/html/wp-content/themes
      - wp-plugins:/var/www/html/wp-content/plugins
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  wp-cli:
    image: wordpress:cli
    user: 33:33
    networks:
      - wp-back
    volumes:
      - htmldata:/var/www/html
      - wp-theme:/var/www/html/wp-content/themes
      - wp-plugins:/var/www/html/wp-content/plugins
      - wp-uploads:/var/www/html/wp-content/uploads
      - db-dump:/var/www/db-dump/
    env_file:
      - .env

  db:
    image: mariadb:latest
    restart: always
    networks:
      - wp-back
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  adminer:
    image: adminer
    networks:
      - wp-back
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080

volumes:
  wp-theme:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/wp-theme
      o: bind

  wp-plugins:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/wp-plugins
      o: bind

  wp-uploads:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/wp-uploads
      o: bind

  htmldata:
  dbdata:
  caddy-data:
  caddy-config:
  db-dump:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/db-dump
      o: bind